# Generated by Django 4.2.7 on 2025-12-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200, verbose_name='Guest Name')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='Guest Email')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='Guest Phone')),
                ('order_type', models.CharField(choices=[('seated', 'Seated Customer'), ('online', 'Online Order')], default='seated', max_length=20, verbose_name='Order Type')),
                ('table_number', models.IntegerField(blank=True, help_text='Only for seated customers', null=True, verbose_name='Table Number')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True, verbose_name='Special Requests/Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Captured at order time', max_length=300, verbose_name='Item Name')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Item Price')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Special Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='restaurant__created_875601_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='restaurant__status_d66ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='restaurant__order_t_7ffe37_idx'),
        ),
    ]
